### PR TITLE
Adds gcc 7 to travis CI

### PR DESCRIPTION
**Pull request by srbcheema1**
This PR adds gcc 7 to Travis file. In reference to the issue #106

### CODE REVIEW

**Comment by cyenyxe** [comment]
It seems the Travis build timed out. Could you please re-run to make sure it wasn't due to an outage in their infrastructure?

**Comment by srbcheema1** [comment]
I too was looking at that thing timed-out thing. I am thinking that gcc 7.3 is not fully stable yet.

**Comment by cyenyxe** [comment]
So it has taken more than 20 minutes to run... I am afraid that will make the Travis builds a lot more unstable, meaning they may fail arbitrarily due to timeouts. We appreciate the work done but we can't merge this unless gcc7 gets faster 😞

**Comment by srbcheema1** [comment]
@cyenyxe I recently saw that the time for gcc 7 build has decreased a lot on Travis. It got down to 15 mins some days back. And now it builds in 13 mins on an average :), which is good I think. I triggered the build thrice and noted an average of 13 mins.
So is it okay to reopen this PR?

**Pull request closed without merging**
