### PR TITLE
clang 3.8 and 3.9 added

### PR DESCRIPTION
**Pull request by InderKaur**
New versions of clang are added to .travis.yml file. #105

### CODE REVIEW

**Comment by jmmut** [comment]
why both 3.8 and 3.9? each compiler we add makes the build slower, so we have to justify each addition. I didn't have time to check which version is used by default in newer linuxes and newer OSXs.

**Comment by cyenyxe** [comment]
Clang 4 and 5 are now supported in Travis, see https://github.com/travis-ci/apt-package-whitelist/pull/3297 and https://github.com/travis-ci/apt-package-whitelist/pull/4034

What I think we should do is to deprecate some of the oldest versions by checking what is the last Ubuntu LTS onwards, and add these more modern ones to the build. I would also keep at least one 3.x version.

**Comment by InderKaur** [comment]
I have done the requested changes. please have a look

**Comment by cyenyxe** [comment]
Any particular reason why you have left the oldest Clang 3.x version?

**Comment by cyenyxe** [comment]
Closed due to lack of activity.

**Pull request closed without merging**
